config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'home#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get 'home/index' => 'home#index', as: :home
  get 'users'=>'users#index'

  resources :profiles do
    resources :stays
  end

  resources :publications do
    member do
      get :add_author
      post 'add_author' => 'publications#add_author_update'
    end

    collection do
      get 'my' => 'publications#my'
      post :add_profile
      get :autocomplete_profile_last_name 
    end
    resources :external_authors
  end

  delete 'publications/:publication_id/author_remove/:id' => 'publications#author_remove', as: :author_remove_publication

  resources :projects do
    get 'my' => 'projects#my', on: :collection
    member do
      patch 'change_status' => 'projects#change_status'
      patch 'draft' => 'projects#change_status', status: '0'
      patch 'confirming' => 'projects#change_status', status: '1'
      patch 'confirmed' => 'projects#change_status', status: '2'
      patch 'archive' => 'projects#change_status', status: '3'
      put 'add_publication' => 'projects#add_publication', as: :add_publication
      delete 'remove_publication' => 'projects#remove_publication', as: :remove_publication
    end
    resources :participants do 
      get :autocomplete_profile_last_name, on: :collection 
    end
    resources :events do
      patch :add_report, on: :member
    end
    resources :researches
    resources :other_events
    resources :edu_programs do
      resources :students
    end
    resources :courses do
      resources :teachers
    end

    resources :expense_periods, shallow: true
    resources :planned_expenses
    resources :reserve_docs
    resources :expense_docs do
      get 'reserve_docs_list', as: :reserve_docs_list, on: :collection
    end
  end
  get 'participants/role_fields_form' => 'participants#role_fields_form', as: :role_fields_form

  resources :roles do
    resources :role_fields do
      resources :role_fields_values
    end
  end

  resources :science_branches
  resources :activity_directions
  resources :rates
  resources :languages
  resources :nationalities

  resources :expense_items
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  audited
  has_and_belongs_to_many :profiles
  has_and_belongs_to_many :projects
  has_many :external_authors, dependent: :destroy
  validates :title, :year, :title_izdanie, presence: true
  validates :year, :numericality => { :greater_than_or_equal_to => 2012 }
  accepts_nested_attributes_for :profiles, :external_authors

  before_save :check

  enum quartile_scopus: [:Q1_sc,:Q2_sc,:Q3_sc,:Q4_sc]
  enum quartile_wos: [:Q1_wos,:Q2_wos,:Q3_wos,:Q4_wos]

  def author
    return Profile.find(self.author_id)
  end

  def authors
    return self.profiles+self.external_authors
  end

  def coauthors
    return self.profiles.where.not(id: self.author_id)+self.external_authors
  end

  def total_cits_scopus_wos
    return self.citations_scopus.to_i+self.citations_wos.to_i+self.citations_scopus_wos.to_i
  end

  private
    def check
      if self.indexed_rinc == false
        self.citations_rinc = nil
      end
      if self.indexed_scopus == false
        self.citations_scopus = nil
        self.quartile_scopus = nil
        self.citations_scopus_wos = nil
      end
      if self.indexed_wos == false
        self.citations_wos = nil
        self.quartile_wos = nil
        self.citations_scopus_wos = nil
      end
    end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  autocomplete :profile, :last_name, :extra_data => [:first_name, :middle_name], :display_value => :fio
  

  def index
    @publications = Publication.all.includes(:external_authors)
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)
    @author = current_user.profile
    @publication.author_id = @author.id

    if @publication.save
      @author.publications << @publication
      @author.save
      redirect_to :action => "my"
    else
      render 'new'
    end
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def my
    # @publications=Publication.where(author_id: current_user.profile.id)
    @publications=current_user.profile.publications.includes(:external_authors)
  end

  def edit
    @publication=Publication.find(params[:id])
  end

  def update
    @publication=Publication.find(params[:id])
    if @publication.update_attributes(publication_params)
      redirect_to :action => "my"
    else
      render 'edit'
    end
  end

  def destroy
    Publication.find(params[:id]).destroy
    flash[:success]='Публикация удалена'
    redirect_to :back
  end

  def add_author
    @publication = Publication.find(params[:id])
  end

  def add_author_update
    @publication = Publication.find(params[:id])
    @profile = Profile.find(params[:profile][:id])

    if @profile.id != @publication.author_id
      @publication.profiles << Profile.find(params[:profile][:id])
    else
      flash[:warning] = 'Такой автор уже есть у этой публикации' 
      render :add_author
      return false
    end

    if @publication.save
      flash[:success]='Автор успешно добавлен.'
      redirect_to action: 'my'
    else
      flash[:error]='Автор не добавлен'
      render :add_author
    end

    rescue ActiveRecord::RecordNotUnique 
      flash[:warning] = 'Такой автор уже есть у этой публикации' 
      render :add_author
    rescue ActiveRecord::RecordNotFound 
      flash[:error] = 'Нет такого автора'
      render :add_author
  end

  def author_remove
    @profile = Profile.find(params[:id])
    @publication = Publication.find(params[:publication_id])
    @publication.profiles.delete(@profile)
    respond_to do |format|
      format.js
    end
  end

  private
  def publication_params
    params.require(:publication).permit!
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_publication_authors.slim
-if publication.author_id?
  p =link_to publication.author.fio,  profile_path(publication.author) 
-if publication.coauthors.present?
  b Соавторы
  -publication.coauthors.each do |coauthor|
    -if coauthor.class == Profile
      p id="profile-#{coauthor.id}"
        =link_to coauthor.fio, profile_path(coauthor)
        -if can? :author_remove, publication
          =link_to author_remove_publication_path(publication, coauthor), method: :delete, remote: true, data: {confirm: "Вы уверены, что хотите удалить автора?"} do
            =fa_icon 'times'
    -else
      p id="external-#{coauthor.id}"
        =coauthor.fio
        -if can? :delete, coauthor
          =link_to publication_external_author_path(publication, coauthor), method: :delete, remote: true, data: {confirm: "Вы уверены, что хотите удалить внешнего автора?"} do
            =fa_icon 'times' 

app/views/publications/_publication_form.slim
= simple_form_for @publication, :html=> {class: 'publication-form'} do |p|
  = p.error_notification
  .form-inputs
    .well В данном разделе добавляются публикации, опубликованные не ранее 2012 года, признак индексируемости, которых соответствует значению «Научные статьи, опубликованные в изданиях, индексируемых в Scopus, Web of Science, РИНС».
    h3 Общие сведения
    .form-group
      =p.input :title
      .form-inline.form-group 
        =p.input :year, input_html: {min: 2012}
      =p.input :url
      =p.input :title_izdanie
      =p.input :url_izdanie
      =p.input :affiliated_fefu
      h3 Автор и соавторы:
      -unless @publication.author_id?
        .well Добавляются после создания публикации
      =render partial: 'publication_authors', locals: {publication: @publication}
      h3 Наукометрические показатели
      .form-inline.form-group        
        =p.input :issn, input_html: {min: 0}
        =p.input :isbn, input_html: {min: 0}
      .form-inline.form-group
        =p.input :indexed_rinc
        =p.input :citations_rinc, disabled: !@publication.indexed_rinc, input_html: {min: 0, id: 'citations_rinc'}, label: 'количество цитирований'
      .form-inline.form-group
        =p.input :indexed_scopus
        =p.input :citations_scopus, disabled: !@publication.indexed_scopus, input_html: {min: 0, id: 'citations_scopus'}, label: 'количество цитирований'
        =p.input :quartile_scopus, disabled: !@publication.indexed_scopus

      .form-inline.form-group
        =p.input :indexed_wos
        =p.input :citations_wos,disabled: !@publication.indexed_wos, input_html: {min: 0, id: 'citations_wos'},label: 'количество цитирований'
        =p.input :quartile_wos, disabled: !@publication.indexed_wos

      .form-inline.form-group
        =p.input :citations_scopus_wos,disabled: !(@publication.indexed_scopus && @publication.indexed_wos), input_html: {min: 0, id: 'citations_scopus_wos'}
  .form-actions
    = p.button :submit, 'Сохранить'
    = link_to "Отмена", my_publications_path, class: 'btn'

app/views/publications/_publication_table.slim
table class="table table-striped"
  thead
    tr
      th id
      th Название
      th Авторы
      th Год издания
      th Аффилирован с ДВФУ
      th Цитирование
      th Управление
  tbody
    -publications.each do |p|
      tr
        td =p.id
        td =link_to p.title, publication_path(p)
        td 
          =render partial: 'publication_authors', locals:{ publication: p }
        td
          =p.year
        td
          =p.affiliated_fefu.humanize
        td
          p
            = 'РИНЦ: '+ p.citations_rinc.to_s if p.citations_rinc.present?
          p
            = 'Scopus: '+ p.citations_scopus.to_s if p.citations_scopus.present?
          p
            = 'WOS: '+ p.citations_wos.to_s if p.citations_wos.present?
          p
            = 'Scopus/WOS: '+ p.citations_scopus_wos.to_s if p.citations_scopus_wos.present?
        td 
          -if can? :edit, p
            p
              =link_to 'Добавить зарегистрированного соавтора', add_author_publication_path(p)
            p
              =link_to 'Добавить внешнего (НЕзарегистриванного) соавтора', new_publication_external_author_path(p)
            p
              =link_to edit_publication_path(p) do
                =fa_icon 'pencil'
                |Редактировать
            p
              -if current_user == p.author.user
                =link_to publication_path(p), method: :delete, data: {confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?"} do
                  =fa_icon 'trash' 
                  |Удалить
          -else
            p
              =link_to publication_path(p) do
                  =fa_icon 'eye'
                  |Просмотр

app/views/publications/add_author.slim
h3 Добавить зарегистрированного автора к публикации "#{@publication.title}"
=simple_form_for :profile, url: add_author_publication_path, methode: :post  do |profile|
  =profile.input :last_name, url: autocomplete_profile_last_name_publications_path, as: :autocomplete, label: 'Поиск по фамилии', :id_element => '#profile_id', placeholder: ' Начните вводить фамилию и выберите из списка предложенных пользователей.'
  =profile.input :id, as: :hidden
  .form-actions
    =profile.button :submit, 'Добавить зарегистрированного автора'
    = link_to "Отмена", my_publications_path, class: 'btn'

app/views/publications/author_remove.js.erb
var profile = $('p#profile-' + <%= @profile.id %>);
profile.remove()

app/views/publications/edit.slim
=render 'publication_form'

app/views/publications/index.slim
-if @publications.present?
  =render partial: 'publication_table', locals: {publications: @publications}

app/views/publications/my.slim
=link_to 'Добавить публикацию', new_publication_path, class: 'btn btn-default'
-if @publications.present?
  =render partial: 'publication_table', locals: {publications: @publications}
-else
  .text-center У вас пока нет публикаций

app/views/publications/new.slim
=render 'publication_form'

app/views/publications/show.slim
-for attribute in @publication.attributes.keys-['id','author_id','created_at','updated_at']
  -enums = @publication.defined_enums.keys
  -if @publication.attributes[attribute].present?
    h4
      = Publication.human_attribute_name(attribute)+':'
    p 
    -if @publication.attributes[attribute].class == TrueClass 
      =@publication.attributes[attribute].humanize
    -elsif enums.include? attribute
      =@publication.send attribute+'_i18n'
    -else
      =@publication.attributes[attribute].to_s