config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'home#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get 'home/index' => 'home#index', as: :home
  get 'users'=>'users#index'

  resources :profiles do
    resources :stays
  end

  resources :publications do
    member do
      get :add_author
      post 'add_author' => 'publications#add_author_update'
    end

    collection do
      get 'my' => 'publications#my'
      post :add_profile
      get :autocomplete_profile_last_name 
    end
    resources :external_authors
  end

  delete 'publications/:publication_id/author_remove/:id' => 'publications#author_remove', as: :author_remove_publication

  resources :projects do
    get 'my' => 'projects#my', on: :collection
    member do
      patch 'change_status' => 'projects#change_status'
      patch 'draft' => 'projects#change_status', status: '0'
      patch 'confirming' => 'projects#change_status', status: '1'
      patch 'confirmed' => 'projects#change_status', status: '2'
      patch 'archive' => 'projects#change_status', status: '3'
      put 'add_publication' => 'projects#add_publication', as: :add_publication
      delete 'remove_publication' => 'projects#remove_publication', as: :remove_publication
    end
    resources :participants do 
      get :autocomplete_profile_last_name, on: :collection 
    end
    resources :events do
      patch :add_report, on: :member
    end
    resources :researches
    resources :other_events
    resources :edu_programs do
      resources :students
    end
    resources :courses do
      resources :teachers
    end

    resources :expense_periods, shallow: true
    resources :planned_expenses
    resources :reserve_docs
    resources :expense_docs do
      get 'reserve_docs_list', as: :reserve_docs_list, on: :collection
    end
  end
  get 'participants/role_fields_form' => 'participants#role_fields_form', as: :role_fields_form

  resources :roles do
    resources :role_fields do
      resources :role_fields_values
    end
  end

  resources :science_branches
  resources :activity_directions
  resources :rates
  resources :languages
  resources :nationalities

  resources :expense_items
end

app/views/shared/_dictionary_form.slim
=simple_form_for object do |f|
  = f.error_notification
  .form-inputs
    =f.input :name
  .form-actions
    =f.submit 'Сохранить', class: 'btn btn-default'

app/views/shared/_flash.slim
-flash.each do |key, value| 
  -unless value.blank?
    div class="alert alert-#{key} %>"
      a href="#" data-dismiss="alert" class="close" ×
      ul
        li
          = value

app/views/shared/_header.slim
header.nav.navbar-default
  .container
    .navbar-header
      =link_to 'Главная', root_path, class: 'navbar-brand'
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span class="sr-only" Toggle navigation
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"

    div id="navbar" class="navbar-collapse collapse" aria-expanded="false"
      ul.nav.navbar-nav
        -if current_user.profile.present?
          li
            =link_to 'Мой профиль', profile_path(current_user.profile.id) 
          li
            =link_to 'Мои публикации', my_publications_path
          li
            =link_to 'Мои проекты', my_projects_path
      ul.nav.navbar-nav.navbar-right
        -if current_user.is_admin?
          li.dropdown
              a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
                |Справочники 
                span.caret
              ul.dropdown-menu
                -if current_user.superadmin?
                  li
                    =link_to 'Пользователи', users_path
                li
                  =link_to 'Профили',profiles_path
                li
                  =link_to 'Публикации', publications_path
                li
                  =link_to 'Проекты', projects_path
                li
                  =link_to 'Научные отрасли', science_branches_path
                li
                  =link_to 'Направления деятельности', activity_directions_path
                li
                  =link_to 'Языки', languages_path
                li
                  =link_to 'Гражданство', nationalities_path
                li
                  =link_to 'Показатели результативности', rates_path
                li
                  =link_to 'Статьи расходов', expense_items_path
                / li
                /   =link_to 'Внешние соавторы', external_autors_path
        li
          =link_to edit_user_registration_path do
            =fa_icon 'user'
            =current_user.login
        li
          =link_to destroy_user_session_path, :method => :delete do
            =fa_icon 'sign-out'
            |Выйти

app/views/shared/_profile_stays.slim
= link_to 'Добавить', new_profile_stay_path(prof) if can? :new, prof.stays
-if prof.stays.present?
  -prof.stays.each do |s|
    p 
      = Russian::strftime(s.from,('%d %B %Y'))+' - '+ Russian::strftime(s.to,('%d %B %Y'))+' '
      -if can? :destroy, s
        = link_to profile_stay_path(prof, s), method: :delete, data: {confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?"} do
          = fa_icon 'times'
-else
  p н/д

app/views/shared/ajax_errors.js.erb
$('body>.container').prepend('<%=j render 'shared/flash', flash: flash%>')