config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'home#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get 'home/index' => 'home#index', as: :home
  get 'users'=>'users#index'

  resources :profiles do
    resources :stays
  end

  resources :publications do
    member do
      get :add_author
      post 'add_author' => 'publications#add_author_update'
    end

    collection do
      get 'my' => 'publications#my'
      post :add_profile
      get :autocomplete_profile_last_name 
    end
    resources :external_authors
  end

  delete 'publications/:publication_id/author_remove/:id' => 'publications#author_remove', as: :author_remove_publication

  resources :projects do
    get 'my' => 'projects#my', on: :collection
    member do
      patch 'change_status' => 'projects#change_status'
      patch 'draft' => 'projects#change_status', status: '0'
      patch 'confirming' => 'projects#change_status', status: '1'
      patch 'confirmed' => 'projects#change_status', status: '2'
      patch 'archive' => 'projects#change_status', status: '3'
      put 'add_publication' => 'projects#add_publication', as: :add_publication
      delete 'remove_publication' => 'projects#remove_publication', as: :remove_publication
    end
    resources :participants do 
      get :autocomplete_profile_last_name, on: :collection 
    end
    resources :events do
      patch :add_report, on: :member
    end
    resources :researches
    resources :other_events
    resources :edu_programs do
      resources :students
    end
    resources :courses do
      resources :teachers
    end

    resources :expense_periods, shallow: true
    resources :planned_expenses
    resources :reserve_docs
    resources :expense_docs do
      get 'reserve_docs_list', as: :reserve_docs_list, on: :collection
    end
  end
  get 'participants/role_fields_form' => 'participants#role_fields_form', as: :role_fields_form

  resources :roles do
    resources :role_fields do
      resources :role_fields_values
    end
  end

  resources :science_branches
  resources :activity_directions
  resources :rates
  resources :languages
  resources :nationalities

  resources :expense_items
end

app/models/project.rb
class Project < ActiveRecord::Base
  audited
  has_many :participants
  has_many :profiles, through: :participants
  has_and_belongs_to_many :publications
  has_and_belongs_to_many :science_branches
  has_and_belongs_to_many :activity_directions
  has_many :events

  #финансы проекта
  has_many :expense_periods
  has_many :planned_expenses, through: :expense_periods
  has_many :expense_items, through: :planned_expenses
  has_many :expense_docs, through: :planned_expenses
  has_many :reserve_docs, through: :planned_expenses
  

  #только для исследовательских и комплексных
  has_many :researches
  accepts_nested_attributes_for :researches

  #только для комплексных
  has_many :other_events

  #только для исследовательских
  has_many :courses
  accepts_nested_attributes_for :courses

  #только для комплексных и образовательных
  has_many :edu_programs
  accepts_nested_attributes_for :edu_programs

  validates :title, :from,:to, presence: true
  validates :from,:to, numericality: { greater_than_or_equal_to: 2015 }
  validate :date_validation

  enum status: {
    draft: 0,
    confirming: 1,
    confirmed: 2,
    archived: 3
  }

  # default_scope { order(created_at: :desc) }

  filterrific(
    available_filters: [
      :with_type
    ]
  )

  scope :with_type, -> (types) { where('type in (?)', types) }

  def self.actual
    return self.where('projects.status != ?', 3)
  end

  def date_validation
    if self.to.present? and self.from.present?
      if self[:to] < self[:from]
        errors[:to] << "Дата окончания должна быть после даты начала"
        return false
      else
        return true
      end
    end
  end

  #Показатели результативности  
  def rate1 #см Rate.find(1)
    return self.publications.where('(publications.quartile_scopus != (3) or publications.quartile_wos != (3)) and (publications.indexed_scopus = 1 or publications.indexed_wos = 1)').size
  end

  def rate2
    return self.rate1
  end

  def rate3
    role_ids = Role.where(name: ['Руководитель проекта','Ведущий ученый','Ключевой член коллектива']).pluck(:id)

    # (Сумма всех цитат в следующих статьях:@1.  входят в б.д.  Scopus,   WoS @2.  Автор статьи-НПР@3.Автор статьи-руководитель либо ведущий ученый либо ключевой член@4.Аффилиация с ДВФУ)
    publs = self.publications.where('(publications.indexed_scopus = 1 or publications.indexed_wos = 1) and publications.affiliated_fefu = 1').joins(profiles: :participants).where('participants.role_id in (?) and participants.status = 0', role_ids).distinct
    #/(Сумма всех статей:@ 1.  входят в б.д.Scopus,WoS @2.Автор статьи-НПР@3.Автор статьи-руководитель либо ведущий ученый либо ключевой член@4.Аффилиация с ДВФУ)
    citaitions_sum = publs.to_a.sum(&:total_cits_scopus_wos).to_f

    return citaitions_sum.to_f/(publs.size.to_f.nonzero? || 1)
  end

  def rate4
    role_ids = Role.where(name: ['Руководитель проекта','Ведущий ученый','Ключевой член коллектива']).pluck(:id)

    #(Сумма всех цитат в следующих статьях:@1.  входят в б.д.  Scopus,   WoS @2.  Автор статьи-НПР@3.Автор статьи-руководитель либо ведущий ученый либо ключевой член@3.Аффилиация с ДВФУ)
    publs = self.publications.where('(publications.indexed_scopus = 1 or publications.indexed_wos = 1) and publications.affiliated_fefu = 1').joins(profiles: :participants).where('participants.role_id in (?) and participants.status = 0', role_ids).distinct
    #/(Сумма всех исполнителей,которые соответствуют следующим критериям:@1.НПР@2.Руководитель либо ведущий ученый либо ключевой член)
    citaitions_sum = publs.to_a.sum(&:total_cits_scopus_wos).to_f
    participants_sum = self.participants.where('participants.role_id in (?) and participants.status = 0', role_ids).size

    return citaitions_sum.to_f/(participants_sum.to_f.nonzero? || 1)
  end

  def rate5
    role_ids = Role.where(name: ['Руководитель проекта','Ведущий ученый','Ключевой член коллектива']).pluck(:id)

    #(Сумма всех исполнителей,которые соответствуют след.критериям:@1.НПР@2.Привлеченный с межд.рынка@3.Руководитель либо ведущий ученый либо@ ключевой член)
    international_participants_sum = self.profiles.where('participants.role_id in (?) and participants.status = 0 and (profiles.labour_market = 1 or profiles.academic_degree = 1)', role_ids).size
    #/(Сумма всех исполнителей,которые  соответствуют след.  критериям:@1.НПР@2.Руководитель либо ведущий ученый либо @ключевой член)
    participants_sum = self.participants.where('participants.role_id in (?) and participants.status = 0', role_ids).size

    return (international_participants_sum.to_f/(participants_sum.to_f.nonzero? || 1)*100)
  end

  def rate6 #Количество обучающихся на основных образовательных программах
    return self.edu_programs.map{|e| e.students.size.to_i}.inject(:+).to_i
  end

  def rate7 #Количество иностранных студентов
    rus = Nationality.find_by_name('Россия')
    return self.edu_programs.map{|e| e.students.where('nationality_id != (?)', rus.id).size.to_i}.inject(:+).to_i
  end

  def rate8
    return 'нет данных'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @projects = Project.unscoped.all.order(created_at: :desc)
    if params[:export_projects].present?
      @projects = @projects.find(params[:export_projects].map(&:to_i))
    else
      @filterrific = initialize_filterrific(
        @projects,
        params[:filterrific],
        select_options: {
          with_type: Project.all.map { |p| [p.type.constantize.model_name.human, p.type] }.uniq
        }
      ) or return
      @projects = @filterrific.find.includes(:participants)
    end

    respond_to do |format|
      format.html
      format.js
      format.xlsx
    end
  end

  def new
    @project  = eval params[:type].camelize+'.new'
    @research = @project.researches.new
    @course = @project.courses.new
  end

  def create
    @project = eval params[:project][:type].camelize+'.new(project_params)'
    @project.status = :draft
    @research = @project.researches.last#объект для ошибок валидации SimpleForm
    @course = @project.courses.last#объект для ошибок валидации SimpleForm

    @project.participants << Participant.new(profile_id: current_user.profile.id, role_id: Role.find_by(name:'Руководитель проекта').id)
    if @project.save
      flash[:success]='Проект создан'
      redirect_to :action => "my"
    else
      flash[:error]= "Вы заполнили не все поля"
      render "new", type: params[:project][:type]
    end
  end

  def edit
    @project = Project.find(params[:id])
    @research = @project.researches.last
    @course = @project.courses.last
  end

  def update
    @project = Project.find(params[:id])
    
    if @project.update_attributes(project_params)

      if params['draft'].present?
        @project.update_attributes(status: 0)
      elsif params['confirming'].present?
        @project.update_attributes(status: 1)
      elsif params['confirmed'].present?
        @project.update_attributes(status: 2)
      elsif params['archive'].present?
        @project.update_attributes(status: 3)
      end

      if current_user.is_admin? 
        redirect_to :action => "index"
      else 
        redirect_to :action => "my"
      end
    else
      render 'edit'
    end
  end

  def show
    @project=Project.find(params[:id])
    @participants = @project.participants.includes(:role)
    @profiles = @project.profiles.includes(:stays)
    @profiles_publications = Publication.joins(:profiles).where('profiles.id in (?)', @profiles.pluck(:id)).uniq.includes(:external_authors, :projects)
    @publications = @project.publications.includes(:external_authors)
    @researches = @project.try(:researches).includes(:science_branches,:activity_directions)
    @events = @project.events.includes(:participant).order(created_at: :desc)
    @edu_programs = @project.edu_programs.includes(:courses, :students).order(created_at: :desc)
    @courses = @project.courses.order(created_at: :desc)
  end

  def my
    @projects = current_user.profile.projects.actual.includes(:participants).uniq
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.draft?
      Project.find(params[:id]).destroy
    else
      flash[:error]='Удалять можно только черновики'
    end
    redirect_to :back
  end

  def change_status
    Project.find(params[:id]).update_attributes(status: params[:status].to_i)
    if current_user.is_admin? 
      redirect_to :action => "index"
    else 
      render "my" 
    end
  end

  def add_publication
    @project = Project.find(params[:id])
    @publication = Publication.find(params[:publication_id])
    @project.publications << @publication
    @project.save
    @publications = @project.publications
    @profiles = @project.profiles
    @profiles_publications = Publication.joins(:profiles).where('profiles.id in (?)', @profiles.pluck(:id)).uniq
    respond_to do |format|
      format.js
    end
  end

  def remove_publication
    @project = Project.find(params[:id])
    @publication = Publication.find(params[:publication_id])
    @project.publications.delete(@publication)
    @publications = @project.publications
    @profiles = @project.profiles
    @profiles_publications = Publication.joins(:profiles).where('profiles.id in (?)', @profiles.pluck(:id)).uniq
    render template: 'projects/add_publication.js.erb'
  end

  private
  def project_params
    params.require(:project).permit!
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_common.slim
-for attribute in @project.attributes.keys-['id','created_at','updated_at']
  -if @project.attributes[attribute].present?
    -enums = @project.defined_enums.keys
    h3
      = Project.human_attribute_name(attribute)+':'
    p 
      -if attribute == 'type'
        =@project.model_name.human
      -elsif enums.include? attribute
        =@project.send attribute+'_i18n'
      -else
        = @project.attributes[attribute].to_s
h3 Направления деятельности: 
-if @project.activity_directions.exists
  p 
    -@project.activity_directions.each do |dir|
      =dir.name+' '
-else
  p не выбраны
h3 Научная(ые) отрасль(и): 
-if @project.science_branches.exists
  p 
    -@project.science_branches.each do |branch|
      =branch.name+' '
-else
  p не выбраны

h3 Показатели результативности:
ol style='padding-left: 20px;'
  -Rate.all.each do |r|
    li
      =r.name
      |: 
      strong 
        =@project.send('rate'+r.id.to_s)

app/views/projects/_project_edu_programs.slim
div style='margin: 10px 0;'
  =link_to 'Добавить образовательную программу', new_project_edu_program_path(@project), class: 'btn btn-default'
  -unless @project.edu_programs.present?
    p.text-center style='margin:40px' Нет образовательных программ
  -else
    table.table.table-striped
      thead
        th Название
        th Курсы
        th Студенты
        / -if can? :edit, @project.edu_programs.first
        th Управление
      tbody
        -@edu_programs.each do |edu_program|
          tr
            td =link_to edu_program.name, project_edu_program_path(@project, edu_program)
            td =render 'edu_programs/edu_program_courses', edu_program: edu_program
            td =render 'edu_programs/edu_program_students', edu_program: edu_program
            / -if can? :edit, edu_program
            td
              p 
                =link_to new_project_course_path(@project, edu_program_id: edu_program.id) do
                  =fa_icon 'plus-circle'
                  | Добавить курс
              p 
                =link_to new_project_edu_program_student_path(@project, edu_program) do
                  =fa_icon 'user-plus'
                  | Добавить студента
              p 
                =link_to edit_project_edu_program_path(@project, edu_program) do 
                  =fa_icon 'pencil'
                  | Редактировать
                p 
                =link_to project_edu_program_path(@project, edu_program), method: :delete, data: {confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?"} do
                  =fa_icon 'trash'
                  | Удалить

app/views/projects/_project_events.slim
div style='margin: 10px 0;'
  =link_to 'Добавить мероприятия',new_project_event_path(@project), class: 'btn btn-default'
  -unless @project.events.present?
    p.text-center style='margin:40px' Нет мероприятий
  -else
    table.table.table-striped
      thead
        th Название
        th Дата начала работ
        th Дата окончания работ
        th Ответственный
        th Статус
        th Отчет о выполнении
        th Дата отчета
        -if can? :edit, @project.events.first
          th Управление
      tbody
        -@events.each do |event|
          tr class='event-#{event.id} '
            td =event.title
            td =Russian::strftime(event.start_date,('%d %B %Y'))
            td =Russian::strftime(event.end_date,('%d %B %Y'))
            td 
              =link_to event.participant.profile.fio, profile_path(event.participant.profile) if event.participant.present?
            td =event.status_i18n
            td.report
              -unless event.report.present? 
                =simple_form_for [@project.becomes(Project), event], url: add_report_project_event_path(@project, event), method: :patch, remote: true do |f|
                  =f.input :report, label: false
                  =f.submit 'Сохранить', class: 'btn btn-default'
              -else
                =event.report
            td.report-date 
              =Russian::strftime(event.report_date,('%d %B %Y')) if event.report_date.present?
            -if can? :edit, event
              td
                =link_to edit_project_event_path(@project, event) do 
                  =fa_icon 'pencil'
                =link_to project_event_path(@project, event), method: :delete, data: {confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?"} do
                  =fa_icon 'trash'

app/views/projects/_project_form.slim
=simple_form_for @project.becomes(Project) do |f|
  =f.error_notification
  .form-group
    h2
      = @project.model_name.human
      small.pull-right =@project.id if @project.id.present?
    =f.input :type, as: :hidden
    =f.input :title
    =f.input :status, disabled: !current_user.is_admin?
    .form-inline
      =f.input :from, input_html: {min: 2015}
      =f.input :to, input_html: {min: 2015}
    =f.association :science_branches
    =f.association :activity_directions
    =f.input :objective
    =f.input :description
    =f.input :results
    =f.input :attracting_additional_funding
    =f.input :experience
    =f.input :resources
    -unless @project.type == 'EduProject'
      h3 Общая информация по исследованию
      =f.simple_fields_for :researches, @research do |r|
        =r.input :theme
        =r.error :theme, id: 'user_name_error'
        =r.association :science_branches
        =r.association :activity_directions
        =r.input :key_words
        =r.input :statement_of_research_problem
        =r.input :aims_and_objectives
        =r.input :desc_research
        =r.input :desc_methods
        =r.input :expected_results
    -if @project.type == 'ResearchProject'
      h3 Учебный курс
      =f.simple_fields_for :courses, @course do |c|
        =c.input :title
        =c.input :lvl
        =c.association :languages
        =c.input :profile_podgotovki
        =c.input :duration
        =c.input :desc
  .form-actions
    = f.button :submit, 'Сохранить'
    = link_to "Отмена", :back, class: 'btn'
    .pull-right
      -if @project.draft?
        = f.button :submit, 'На согласование', name: 'confirming'
      -elsif @project.confirming? && current_user.is_admin?
        = f.button :submit, 'Cогласован', name: 'confirmed'
      -elsif @project.confirmed? && current_user.is_admin?
        = f.button :submit, 'В архив', name: 'archive'

app/views/projects/_project_other_events.slim
div style='margin: 10px 0;'
  =link_to 'Добавить иное мероприятия', new_project_other_event_path(@project), class: 'btn btn-default'
  -unless @project.other_events.present?
    p.text-center style='margin:40px' Нет иных мероприятий
  -else
    table.table.table-striped
      thead
        th Название
        -if can? :edit, @project.other_events.first
          th Управление
      tbody
        -@project.other_events.order(created_at: :desc).each do |other_event|
          tr
            td =link_to other_event.name, project_other_event_path(@project, other_event)
            -if can? :edit, other_event
              td
                =link_to edit_project_other_event_path(@project, other_event) do 
                  =fa_icon 'pencil'
                =link_to project_other_event_path(@project, other_event), method: :delete, data: {confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?"} do
                  =fa_icon 'trash'

app/views/projects/_project_planned_expenses.slim
=link_to 'Добавить плановый расход', new_project_planned_expense_path(@project), class: 'btn btn-default'

table.table.table-striped
  thead
    tr
      th = PlannedExpense.human_attribute_name('expense_period')
      th = PlannedExpense.human_attribute_name('expense_item')
      th = PlannedExpense.human_attribute_name('value')
      th Управление

  tbody
    - planned_expenses.each do |planned_expense|
      tr
        td = link_to planned_expense.expense_period.period, expense_period_path(planned_expense.expense_period)        
        td = link_to planned_expense.expense_item.code+' - '+planned_expense.expense_item.name, expense_item_path(planned_expense.expense_item)
        td = planned_expense.value
        td
          ul.list
            li
              = link_to project_planned_expense_path(@project, planned_expense) do
                =fa_icon 'eye'
                |Просмотр
            li
              = link_to edit_project_planned_expense_path(@project, planned_expense) do
                =fa_icon 'pencil'
                |Редактировать
            li
              = link_to  project_planned_expense_path(@project, planned_expense), data: { confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?" }, method: :delete do
                =fa_icon 'trash'
                |Удалить

app/views/projects/_project_profiles_publications.slim
h3 Все публикации участников
table.table.table-striped
    thead
      th Название
      th Год издания
      th Авторы
      th Добавить в проект
    tbody
      -profiles_publications.each do |publ|
          tr 
            td =link_to publ.title, publication_path(publ)
            td =publ.year
            td =render partial: 'publications/publication_authors', locals: { publication: publ }
            td 
              -unless publ.projects.present?
                =link_to 'Добавить в проект', add_publication_project_path(@project, publication_id: publ), method: :put, remote: :true
              -else
                p 
                  |Уже добавлена в проект 
                  -publ.projects.each do |pr|
                    =link_to pr.title, project_path(pr)

app/views/projects/_project_researches.slim
div style='margin: 10px 0'
  =link_to 'Добавить исследование', new_project_research_path(@project), class: 'btn btn-default'
-unless @researches.present?
  p.text-center style='margin:40px' Нет исследований
-else
  table.table.table-striped
    thead
      th Тема
      th Научная(ые) отрасль(и)
      th Направления исследований и образовательных программ 
      -if can? :edit, @researches.new
        th Управление
    tbody
      -@researches.each do |res|
        tr 
          td = link_to res.theme, project_research_path(@project, res)
          td 
            -res.science_branches.each do |i|
              p =i.name
          td 
            -res.activity_directions.each do |i|
              p =i.name
          -if can? :edit, res
            td
              =link_to edit_project_research_path(@project, res) do 
                =fa_icon 'pencil'
              =link_to project_research_path(@project, res), method: :delete, data: {confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?"} do
                =fa_icon 'trash'

app/views/projects/_project_reserve_docs.slim
=link_to 'Добавить резервный документ', new_project_reserve_doc_path(@project), class: 'btn btn-default'

table.table.table-striped
  thead
    tr
      th Период
      th Статья расхода
      th Плановая сумма
      th = ReserveDoc.human_attribute_name('date')
      th = ReserveDoc.human_attribute_name('number')
      th = ReserveDoc.human_attribute_name('cfo')
      th = ReserveDoc.human_attribute_name('contragent')
      th = ReserveDoc.human_attribute_name('payment_purpose')
      th = ReserveDoc.human_attribute_name('sum')
      th = ReserveDoc.human_attribute_name('from')
      th = ReserveDoc.human_attribute_name('to')
      th = ReserveDoc.human_attribute_name('responsible')
      th = ReserveDoc.human_attribute_name('comment')
      th Управление

  tbody
    - reserve_docs.each do |reserve_doc|
      tr
        td = link_to reserve_doc.planned_expense.expense_period.period, reserve_doc.planned_expense.expense_period
        td = link_to reserve_doc.planned_expense.expense_item.human_name, reserve_doc.planned_expense.expense_item
        td = link_to reserve_doc.planned_expense.value, [@project.becomes(Project), reserve_doc.planned_expense]
        td = reserve_doc.date
        td = reserve_doc.number
        td = reserve_doc.cfo
        td = reserve_doc.contragent
        td = reserve_doc.payment_purpose
        td = reserve_doc.sum
        td = reserve_doc.from
        td = reserve_doc.to
        td = reserve_doc.responsible
        td = reserve_doc.comment
        td
          ul.list
            li
              = link_to project_reserve_doc_path(@project, reserve_doc) do
                =fa_icon 'eye'
                |Просмотр
            li
              = link_to edit_project_reserve_doc_path(@project, reserve_doc) do
                =fa_icon 'pencil'
                |Редактировать
            li
              = link_to  project_reserve_doc_path(@project, reserve_doc), data: { confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?" }, method: :delete do
                =fa_icon 'trash'
                |Удалить

app/views/projects/add_publication.js.erb
$('#project-publications').html('<%=j render 'project_publications_table', publications: @publications%>')
$('#project-profiles-publications').html('<%=j render 'project_profiles_publications', profiles_publications: @profiles_publications%>')

app/views/projects/index.slim
= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f|
  = f.collection_check_boxes :with_type, @filterrific.select_options[:with_type], :last, :first
  = f.submit 'Применить', class: "btn btn-default"
  = render_filterrific_spinner 

= form_tag projects_path(format: :xlsx), method: :get
  .btn-group
    .btn-group
      a type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
        |Создать проект 
        span.caret
      ul.dropdown-menu
        li
          =link_to 'Комплексный', new_project_path(type: 'complex_project')
        li
          =link_to 'Исследовательский', new_project_path(type: 'research_project')
        li
          =link_to 'Образовательный', new_project_path(type: 'edu_project')
    / = link_to projects_path(format: :xlsx), class: 'btn btn-default' do 
    = button_tag(type: "submit", class: 'btn btn-default') do
      = fa_icon 'file-excel-o'
      |Скачать отчет

  = render 'projects_table', projects: @projects

app/views/projects/my.slim
.btn-group
  button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
    |Создать проект 
    span.caret
  ul.dropdown-menu
    li
      =link_to 'Комплексный', new_project_path(type: 'complex_project')
    li
      =link_to 'Исследовательский', new_project_path(type: 'research_project')
    li
      =link_to 'Образовательный', new_project_path(type: 'edu_project')

-unless current_user.profile.projects.present?
  .text-center У вас нет проектов
-else
  =render 'projects_table', projects: @projects

app/views/projects/new.slim
=render 'project_form'

app/views/projects/show.slim
h1 
  |Проект 
  =@project.title+' '
  small =@project.status_i18n
  -if can? :edit, @project
    .pull-right
      =link_to edit_project_path(@project) do 
        =fa_icon 'pencil'
ul.nav.nav-tabs
  li.active 
    a data-toggle="tab" href="#common" Общие сведения
  li
    a data-toggle="tab" href="#participants" Участники проекта
  li
    a data-toggle="tab" href="#publications" Публикации проекта
  li
    a data-toggle="tab" href="#events" Календарный план

  -unless @project.type == 'EduProject'
    li
      a data-toggle="tab" href="#researches" Исследования

  -if @project.type == 'ResearchProject'
    li
      a data-toggle="tab" href="#courses" Учебный курс

  -if @project.type == 'ComplexProject'
    li
      a data-toggle="tab" href="#other_events" Иные мероприятия

  -if @project.type == 'ComplexProject' || 'EduProject'
    li
      a data-toggle="tab" href="#edu_programs" Обр-ые программы

  li
    a data-toggle="tab" href="#finances" Финансы

.tab-content
  #common.tab-pane.fade.in.active
    =render 'project_common'
    
  #participants.tab-pane.fade.in
     =render 'project_participants'

  #publications.tab-pane.fade.in
    #project-publications
      -if @publications.present?
        =render 'project_publications_table', publications: @publications
      -else
        p.text-center style='margin:40px' Нет включенных в проект публикаций
    #project-profiles-publications
      =render 'project_profiles_publications', profiles_publications: @profiles_publications
     
  #events.tab-pane.fade.in
    =render 'project_events'

  -unless @project.type == 'EduProject'
    #researches.tab-pane.fade.in
      =render 'project_researches'

  -if @project.type == 'ComplexProject'
    #other_events.tab-pane.fade.in
      =render 'project_other_events'

  -if @project.type == 'ResearchProject'
    #courses.tab-pane.fade.in
      =render 'project_courses'

  -if @project.type == 'ComplexProject' || 'EduProject'
    #edu_programs.tab-pane.fade.in
      =render 'project_edu_programs'

  #finances.tab-pane.fade.in
    =render 'project_finances'