config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'home#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get 'home/index' => 'home#index', as: :home
  get 'users'=>'users#index'

  resources :profiles do
    resources :stays
  end

  resources :publications do
    member do
      get :add_author
      post 'add_author' => 'publications#add_author_update'
    end

    collection do
      get 'my' => 'publications#my'
      post :add_profile
      get :autocomplete_profile_last_name 
    end
    resources :external_authors
  end

  delete 'publications/:publication_id/author_remove/:id' => 'publications#author_remove', as: :author_remove_publication

  resources :projects do
    get 'my' => 'projects#my', on: :collection
    member do
      patch 'change_status' => 'projects#change_status'
      patch 'draft' => 'projects#change_status', status: '0'
      patch 'confirming' => 'projects#change_status', status: '1'
      patch 'confirmed' => 'projects#change_status', status: '2'
      patch 'archive' => 'projects#change_status', status: '3'
      put 'add_publication' => 'projects#add_publication', as: :add_publication
      delete 'remove_publication' => 'projects#remove_publication', as: :remove_publication
    end
    resources :participants do 
      get :autocomplete_profile_last_name, on: :collection 
    end
    resources :events do
      patch :add_report, on: :member
    end
    resources :researches
    resources :other_events
    resources :edu_programs do
      resources :students
    end
    resources :courses do
      resources :teachers
    end

    resources :expense_periods, shallow: true
    resources :planned_expenses
    resources :reserve_docs
    resources :expense_docs do
      get 'reserve_docs_list', as: :reserve_docs_list, on: :collection
    end
  end
  get 'participants/role_fields_form' => 'participants#role_fields_form', as: :role_fields_form

  resources :roles do
    resources :role_fields do
      resources :role_fields_values
    end
  end

  resources :science_branches
  resources :activity_directions
  resources :rates
  resources :languages
  resources :nationalities

  resources :expense_items
end

app/models/reserve_doc.rb
class ReserveDoc < ActiveRecord::Base
  belongs_to :planned_expense
  has_many :expense_docs, dependent: :nullify

  NON_VALIDATABLE_ATTRS = ["id", "created_at", "updated_at", 'comment'] 
  VALIDATABLE_ATTRS = ReserveDoc.attribute_names.reject{|attr| NON_VALIDATABLE_ATTRS.include?(attr)}

  validates_presence_of VALIDATABLE_ATTRS
  validate :date_within_periods_dates, :sum_within_planned_value

  def date_within_periods_dates
    errors[:from] << 'Неправильная дата' if self.from < self.planned_expense.expense_period.start
    errors[:to] << 'Неправильная дата' if self.to > self.planned_expense.expense_period.finish
  end

  def sum_within_planned_value
    errors[:sum] << 'Превышен лимит.' if self.sum > self.planned_expense.balance_res
  end

  def human_name
    return '№ '+self.number+' Сумма: '+self.sum.to_s
  end
end

app/controllers/reserve_docs_controller.rb
class ReserveDocsController < ApplicationController
  before_action :set_reserve_doc, only: [:show, :edit, :update, :destroy]

  # GET /reserve_docs
  def index
    @reserve_docs = ReserveDoc.all
  end

  # GET /reserve_docs/1
  def show
  end

  # GET /reserve_docs/new
  def new
    @project = Project.find(params[:project_id])
    @reserve_doc = ReserveDoc.new
  end

  # GET /reserve_docs/1/edit
  def edit
  end

  # POST /reserve_docs
  def create
    @project = Project.find(params[:project_id])
    @reserve_doc = ReserveDoc.new(reserve_doc_params)

    if @reserve_doc.save
      redirect_to project_path(@project, anchor: 'finances'), notice: 'Резервный документ успешно создан.'
    else
      render :new
    end
  end

  # PATCH/PUT /reserve_docs/1
  def update
    if @reserve_doc.update(reserve_doc_params)
      redirect_to project_path(@project, anchor: 'finances'), notice: 'Резервный документ успешно обновлен.'
    else
      render :edit
    end
  end
  
  # DELETE /reserve_docs/1
  def destroy
    @reserve_doc.destroy
    redirect_to project_path(@project, anchor: 'finances'), notice: 'Резервный документ успешно удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserve_doc
      @project = Project.find(params[:project_id])
      @reserve_doc = ReserveDoc.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def reserve_doc_params
      params.require(:reserve_doc).permit(:planned_expense_id, :date, :number, :cfo, :contragent, :payment_purpose, :sum, :from, :to, :responsible, :comment)
    end
end

app/helpers/reserve_docs_helper.rb
module ReserveDocsHelper
  def reserve_docs_collection_for_select
    return @project.reserve_docs.map {|r| [ '№ '+r.number+' Сумма: '+r.sum.to_s, r.id ] }
  end
end

app/views/reserve_docs/_form.html.slim
= simple_form_for [@project.becomes(Project),@reserve_doc] do |f|
  = f.error_notification

  .form-inputs
    = f.association :planned_expense, collection: planned_expense_collection_for_select
    = f.input :date
    = f.input :number
    = f.input :cfo
    = f.input :contragent
    = f.input :payment_purpose
    = f.input :sum
    = f.input :from
    = f.input :to
    = f.input :responsible
    = f.input :comment

  .form-actions.btn-group
    = f.button :submit, 'Сохранить'
    = link_to 'Назад', project_path(@project, anchor: 'finances'), class: 'btn btn-default'

app/views/reserve_docs/edit.html.slim
h1 
  |Редактирование reserve_doc
  .pull-right
    =link_to project_reserve_doc_path(@project, @reserve_doc) do
      =fa_icon 'eye'
== render 'form'

app/views/reserve_docs/index.html.slim
h1 reserve_docs

=link_to 'Добавить', new_reserve_doc_path, class: 'btn btn-default'

table.table.table-striped
  thead
    tr
      th = ReserveDoc.human_attribute_name('planned_expense_id,')
      th = ReserveDoc.human_attribute_name('date,')
      th = ReserveDoc.human_attribute_name('number,')
      th = ReserveDoc.human_attribute_name('cfo,')
      th = ReserveDoc.human_attribute_name('contragent,')
      th = ReserveDoc.human_attribute_name('payment_purpose,')
      th = ReserveDoc.human_attribute_name('sum,')
      th = ReserveDoc.human_attribute_name('from,')
      th = ReserveDoc.human_attribute_name('to,')
      th = ReserveDoc.human_attribute_name('responsible,')
      th = ReserveDoc.human_attribute_name('comment')
      th Управление

  tbody
    - @reserve_docs.each do |reserve_doc|
      tr
        td = reserve_doc.planned_expense_id,
        td = reserve_doc.date,
        td = reserve_doc.number,
        td = reserve_doc.cfo,
        td = reserve_doc.contragent,
        td = reserve_doc.payment_purpose,
        td = reserve_doc.sum,
        td = reserve_doc.from,
        td = reserve_doc.to,
        td = reserve_doc.responsible,
        td = reserve_doc.comment
        td
          ul.list
            li
              = link_to reserve_doc do
                =fa_icon 'eye'
                |Просмотр
            li
              = link_to edit_reserve_doc_path(reserve_doc) do
                =fa_icon 'pencil'
                |Редактировать
            li
              = link_to  reserve_doc, data: { confirm: "Это действие необратимо! Вы уверены, что хотите продолжить?" }, method: :delete do
                =fa_icon 'trash'
                |Удалить

app/views/reserve_docs/new.html.slim
h1 Создать reserve_doc

== render 'form'

app/views/reserve_docs/show.html.slim
h2 
  |Резервный документ
  .pull-right
    =link_to edit_project_reserve_doc_path(@project, @reserve_doc) do
      =fa_icon 'pencil'

-for attribute in @reserve_doc.attributes.keys-['id', 'created_at','updated_at']
  -if @reserve_doc.attributes[attribute].present?
    -enums = @reserve_doc.defined_enums.keys
    p
      strong
        = ReserveDoc.human_attribute_name(attribute)+': '
      -if enums.include? attribute
        =@reserve_doc.send attribute+'_i18n'
      -elsif attribute == 'planned_expense_id'
        -pl = PlannedExpense.find(@reserve_doc.attributes[attribute])
        =link_to pl.name, [@project.becomes(Project), pl]
      -else
       = @reserve_doc.attributes[attribute].to_s

.btn-group
  = link_to 'Назад', :back, class: 'btn btn-default'